export enum ROUTE {
  HOME = "/",
  SEARCH = "/search",
  SIGN_IN = "/sign-in",
  SIGN_UP = "/sign-up",
  RESTORE_PASSWORD = "/sign-in/restore-password",
  ATRICLES_DETAILS = "/articles/:id",
  NEWS_DETAILS = "/blogs/:id",
  ARTICLES = "/articles",
  ARTICLES_PAGES = "/articles/:page",
  SEARCH_ARTICLES = "/articles/:title_contains",
  NEWS_PAGES = "/blogs/:page",
  SEARCH_NEWS = "/blogs/:title_contains",
  NEWS = "/blogs",
  ACCOUNT = "/account",
  NOT_FOUND = "*",
}
