export enum ROUTE {
    HOME = '/',
    SEARCH = '/search',
    SIGN_IN = '/sign-in',
    SIGN_UP = '/sign-up',
    RESTORE_PASSWORD = '/sign-in/restore-password',
    ATRICLES_DETAILS = '/articles/:id',
    NEWS_DETAILS = '/blogs/:id',
    ARTICLES_PAGES = '/articles/:page',
    ARTICLES = '/articles',
    NEWS_PAGES = '/blogs/:page',
    NEWS = '/blogs',
    ACCOUNT = '/account',
    NOT_FOUND = '*',
}