export enum ROUTE {
    HOME = '/',
    SEARCH = '/search',
    SIGN_IN = '/sign-in',
    SIGN_UP = '/sign-up',
    RESTORE_PASSWORD = '/sign-in/restore-password',
    ATRICLES_DETAILS = '/articles/:id',
    NEWS_DETAILS = '/blog/:id',
    ATRICLES_PAGES = '/articles/:page',
    ARTICLES = '/articles',
    NEWS_PAGES = '/blog/:page',
    NEWS = '/blog',
    ACCOUNT = '/account',
    NOT_FOUND = '*',
}